# MQTT Settings
KEEP_ALIVE = 60  # seconds

MQTT_BROKER = "test.mosquitto.org"
MQTT_PORT = 1883

# -------BASE TOPIC-------------

MQTT_TOPIC_BASE = 'IoTAQStation'
MQTT_ALL_TOPIC = MQTT_TOPIC_BASE + '/#'
MQTT_RESPONSE_TOPIC = "IoTAQStation/Responses"

# -------ZONE TOPICS-------------

MQTT_TOPIC_ZONE = MQTT_TOPIC_BASE + '/Zones'

# -------SENSORS TOPICS-------------

MQTT_TOPIC_SENSORS_L = MQTT_TOPIC_BASE + '/Zones/'
MQTT_TOPIC_SENSORS_R = '/Sensors/'
MQTT_SENSORS = MQTT_TOPIC_BASE + '/Sensors/Device_id'
MQTT_ALL_DEVICES = MQTT_TOPIC_BASE + '/Sensors/#'
MQTT_REQUEST_BROADCAST = MQTT_ALL_DEVICES

# -------BARRIER TOPICS-------------
MQTT_BARRIER_CONTROL = MQTT_TOPIC_BASE + '/Barriers'
MQTT_BARRIER_CONTROL_L = MQTT_TOPIC_BASE + '/Zones/'
MQTT_BARRIER_CONTROL_R = '/Barriers/'
MQTT_BARRIER_STATUS = MQTT_BARRIER_CONTROL_L + '/+/Status'
